version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: covid
      POSTGRES_USER: covid
      POSTGRES_PASSWORD: ${PG_PWD}
    container_name: "postgres"
    ports:
      - "5432:5432"
  covidexercise:
    image: "sri2441/exercise:1.0"
    container_name: "reporting"
    depends_on:
      - postgres
    environment:
      PG_PWD: ${PG_PWD}
    ports:
      - "9000:9000"

# for testing
  pgadmin:
    image: dpage/pgadmin4
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"